AAKD, I want linting in CI on the auto ML project
kili-technology/automl pull request #11
Opened 2022-03-28 11:54 UTC by crsegerie

2022-03-28 12:36 UTC, crsegerie commented
end 2 end tests passing

2022-03-28 13:17 UTC, PierreLeveau requested changes

2022-03-28 13:17 UTC, PierreLeveau commented on contributing.md
> +
install grammarly to fix typos and syntax errors.

2022-03-28 13:17 UTC, PierreLeveau commented
also trying locally to see if the installation procedure works.

2022-03-28 13:43 UTC, crsegerie commented
I've tested the black formatting, and even with a correctable modification, black fails in the GitHub action. So it's working as expected.

2022-03-28 14:43 UTC, PierreLeveau requested changes

2022-03-28 14:43 UTC, PierreLeveau commented on contributing.md
> +## Help us to help you!
For now, you can keep the contributing.md to the minimum (no policy yet about external contributions).

```
# Contributing 

## Development environment
To install the development environment, please follow these steps:
```bash
pip install -r requirements_dev.txt
pre-commit install
pre-commit run --all-files
```

2022-03-29 07:08 UTC, PierreLeveau approved these changes

2022-03-29 07:08 UTC, merged