Feature/ml 351 text classification notebook
kili-technology/automl pull request #84
Opened 2022-06-13 09:50 UTC by antonioloison

- Add notebook for text classification
- Replace single quotes with double in image classification notebook
- Warning: Label Error is not available for text classification so this part is not in the notebook

2022-06-17 08:55 UTC, antonioloison commented
Missing colab link in README

2022-06-20 09:59 UTC, PierreLeveau commented
2 modifications to do in the notebook:
* rm:
`!pip install kili`
(dependency already included in AutoML)

* 
```
 description="Classify sentiment in IMDB Reviews,
```

2022-06-21 09:05 UTC, PierreLeveau requested changes

2022-06-21 09:07 UTC, PierreLeveau commented
the colab links are wrong

2022-06-21 09:14 UTC, PierreLeveau approved these changes

2022-06-21 09:15 UTC, merged